### ISSUE TITLE
tomcat7:run SEVERE: Unable to process Jar entry from JAR for annotations

### ISSUE THREAD

**Issue by grigory-lobkov** [grigory-lobkov/timerec#1]
Console error for jar:file:/C:/Users/Grigory/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar!/

> Jun 06, 2020 10:44:26 AM org.apache.catalina.startup.ContextConfig processAnnotationsJar
> **SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/C:/Users/Grigory/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar!/] for annotations**
> org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
> 	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:133)
> 	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:60)
> 	at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:209)
> 	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:119)
> 	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2134)
> 	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2010)
> 	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1976)
> 	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1961)
> 	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1319)
> 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:878)
> 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:376)
> 	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
> 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by touatiosema** [comment]
I had the same issue on tomcat8.
```

org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:55)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:177)
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:85)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2011)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1961)
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1936)
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1897)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1149)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:771)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5066)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
